[package]
name = "broadsword_microsoft_static_analysis"
version = "0.0.1"
edition = "2021"

[dependencies]
pelite = "0.10"
broadsword_rtti = { path = "../rtti" }
broadsword_address = { path = "../../address" }
