[workspace]
members = [
    "exports",
    "crates/scanner",
    "crates/microsoft/rtti",
    "crates/microsoft/dll",
    "crates/microsoft/debug",
    "crates/microsoft/runtime",
    "mod/crash-logger",
]

[workspace.dependencies]
log = "0.4"
log4rs = "1"
