[package]
name = "offline-aob"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
rayon = "1"
iced-x86 = "1"
pelite = "0.10"
serde_json = "1"
indicatif = { version = "0.17.5", features = ["rayon"]}
serde = { workspace = true }
broadsword = { path = "../../exports" }