[package]
name = "virtual-destructor-finder"
version = "0.1.0"
edition = "2021"

[dependencies]
pelite = "0.10"
graphviz-rust = "0.6"
regex = "1.7"
msvc-demangler = "0.9"
broadsword = { path = "../../exports" }
iced-x86 = { version = "1.19.0", features = ["decoder"] }
