[package]
name = "broadsword_logging"
version = "0.0.1"
edition = "2021"

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"

[dependencies]
log = { workspace = true }
log4rs = { workspace = true }
log-panics = { version = "2", features = ["with-backtrace"]}