[package]
name = "allocator-log-splitter"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.160"
bincode = "1.3.3"
indicatif = "0.17.3"
eldenring_allocator_hook = { path = "../../mod/eldenring/allocator-hook" }
